### ISSUE TITLE
Subscribe to Yii Software

### ISSUE THREAD

**Issue by Mister-42** [follow-github-organisation/follow-github-organisation#283]
## Paste the link of the GitHub organisation below and submit
https://github.com/yiisoft

---

###### Please subscribe to this thread to get notified when a new repository is created

---
# Looking for an easy way? Check out [followgithub.org](https://followgithub.org)

**Comment by pravj** [comment]
Hi @Mister-42,

How are you doing?

Just wanted to inform you that I've discontinued the service as I wasn't able to manage it properly (both from a time and cost point of view). Extremely sorry for the inconvenience.
