### ISSUE TITLE
Subscribe to Facebook Research

### ISSUE THREAD

**Issue by ScriptSmith** [follow-github-organisation/follow-github-organisation#36]
## Paste the link of the GitHub organisation below and submit
https://github.com/facebookresearch

---

**Comment by followgithuborg** [comment]
Great! I will take care of it from now onwards.
Please subscribe to this thread so you can get notifications.

**Comment by followgithuborg** [comment]
1 new repository created in [Facebook Research](https://github.com/facebookresearch)
* [M3RL](https://github.com/facebookresearch/M3RL)

**Comment by followgithuborg** [comment]
1 new repository created in [Facebook Research](https://github.com/facebookresearch)
* [measuring-emergent-comm](https://github.com/facebookresearch/measuring-emergent-comm)

**Comment by followgithuborg** [comment]
1 new repository created in [Facebook Research](https://github.com/facebookresearch)
* [multigrain](https://github.com/facebookresearch/multigrain)

**Comment by followgithuborg** [comment]
1 new repository created in [Facebook Research](https://github.com/facebookresearch)
* [multigrain](https://github.com/facebookresearch/multigrain)

**Comment by followgithuborg** [comment]
1 new repository created in [Facebook Research](https://github.com/facebookresearch)
* [multigrain](https://github.com/facebookresearch/multigrain)

**Comment by followgithuborg** [comment]
1 new repository created in [Facebook Research](https://github.com/facebookresearch)
* [multigrain](https://github.com/facebookresearch/multigrain)

**Comment by followgithuborg** [comment]
1 new repository created in [Facebook Research](https://github.com/facebookresearch)
* [multigrain](https://github.com/facebookresearch/multigrain)

**Comment by followgithuborg** [comment]
1 new repository created in [Facebook Research](https://github.com/facebookresearch)
* [LAMA](https://github.com/facebookresearch/LAMA)

**Comment by followgithuborg** [comment]
1 new repository created in [Facebook Research](https://github.com/facebookresearch)
* [LAMA](https://github.com/facebookresearch/LAMA)

**Comment by followgithuborg** [comment]
1 new repository created in [Facebook Research](https://github.com/facebookresearch)
* [LAMA](https://github.com/facebookresearch/LAMA)

**Comment by followgithuborg** [comment]
1 new repository created in [Facebook Research](https://github.com/facebookresearch)
* [OctConv](https://github.com/facebookresearch/OctConv)

**Comment by followgithuborg** [comment]
1 new repository created in [Facebook Research](https://github.com/facebookresearch)
* [music-translation](https://github.com/facebookresearch/music-translation)

**Comment by followgithuborg** [comment]
1 new repository created in [Facebook Research](https://github.com/facebookresearch)
* [music-translation](https://github.com/facebookresearch/music-translation)

**Comment by followgithuborg** [comment]
1 new repository created in [Facebook Research](https://github.com/facebookresearch)
* [music-translation](https://github.com/facebookresearch/music-translation)

**Comment by followgithuborg** [comment]
1 new repository created in [Facebook Research](https://github.com/facebookresearch)
* [music-translation](https://github.com/facebookresearch/music-translation)

**Comment by followgithuborg** [comment]
1 new repository created in [Facebook Research](https://github.com/facebookresearch)
* [stochastic_gradient_push](https://github.com/facebookresearch/stochastic_gradient_push)

**Comment by followgithuborg** [comment]
1 new repository created in [Facebook Research](https://github.com/facebookresearch)
* [stochastic_gradient_push](https://github.com/facebookresearch/stochastic_gradient_push)

**Comment by followgithuborg** [comment]
1 new repository created in [Facebook Research](https://github.com/facebookresearch)
* [stochastic_gradient_push](https://github.com/facebookresearch/stochastic_gradient_push)

**Comment by pravj** [comment]
Deleting this issue as requested by @ScriptSmith
